# Generated by Django 5.0.4 on 2024-04-20 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paciente.consulta')),
            ],
        ),
    ]
