# Generated by Django 5.0.4 on 2024-04-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='status_pagto',
            field=models.CharField(choices=[('A', 'Agendada'), ('F', 'Finalizada'), ('C', 'Cancelada'), ('I', 'Iniciada')], default='A', max_length=1),
        ),
    ]
