# Generated by Django 5.0.4 on 2024-04-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_consulta_status_pagto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='status_pagto',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1),
        ),
    ]
